#pragma once
#include "../Domain/Models.mqh"
#include "../Core/Hash.mqh"
#include "Preflight.mqh"
#include "../Persistence/Repositories.mqh"
class AS_ExecutionEngine {
private: AS_Preflight m_preflight; AS_Repositories *m_repo; AS_ExecutionRecord m_current;
public:
   AS_ExecutionEngine(void){m_repo=NULL;ZeroMemory(m_current);m_current.state=AS_EXEC_IDLE;}
   void Attach(AS_Repositories &repo){m_repo=&repo;m_repo.LoadLatestUnresolvedExecution(m_current);}
   bool HasUnresolved()const{return m_current.state==AS_EXEC_SUBMITTING||m_current.state==AS_EXEC_ACCEPTED||m_current.state==AS_EXEC_PARTIALLY_FILLED||m_current.state==AS_EXEC_UNKNOWN||m_current.state==AS_EXEC_RECONCILING;}
   AS_ExecutionRecord Current()const{return m_current;}
   bool SubmitDemo(const AS_TradePlan &p,string &reason){ if(HasUnresolved()){reason="EXECUTION_ALREADY_UNRESOLVED";return false;} MqlTradeRequest req;MqlTradeCheckResult chk;if(!m_preflight.Validate(p,req,chk,reason))return false; m_current.execution_id=AS_Fnv1a(p.plan_id+"|"+IntegerToString((int)TimeCurrent()));m_current.plan_id=p.plan_id;m_current.signal_id=p.signal_id;m_current.symbol=p.symbol;m_current.state=AS_EXEC_SUBMITTING;m_current.requested_volume=p.lot_size;m_current.updated_at=TimeCurrent();m_current.terminal=false; MqlTradeResult result;ZeroMemory(result);bool sent=OrderSend(req,result);m_current.request_id=result.request_id;m_current.order_ticket=result.order;m_current.deal_ticket=result.deal;m_current.retcode=result.retcode;m_current.message=result.comment;m_current.updated_at=TimeCurrent(); if(!sent){m_current.state=AS_EXEC_REJECTED;m_current.terminal=true;reason=StringFormat("ORDERSEND_%u_%s",result.retcode,result.comment);}else if(result.retcode==TRADE_RETCODE_DONE){m_current.state=AS_EXEC_FILLED;}else if(result.retcode==TRADE_RETCODE_DONE_PARTIAL){m_current.state=AS_EXEC_PARTIALLY_FILLED;}else if(result.retcode==TRADE_RETCODE_PLACED){m_current.state=AS_EXEC_ACCEPTED;}else{m_current.state=AS_EXEC_UNKNOWN;reason=StringFormat("UNKNOWN_SUBMIT_%u_%s",result.retcode,result.comment);} if(m_repo!=NULL)m_repo.SaveExecution(m_current);return sent; }
   void OnTransaction(const MqlTradeTransaction &trans,const MqlTradeRequest &request,const MqlTradeResult &result){ if(m_current.execution_id=="")return; bool related=false;if(m_current.request_id>0&&result.request_id==m_current.request_id)related=true;if(m_current.order_ticket>0&&trans.order==m_current.order_ticket)related=true;if(m_current.deal_ticket>0&&trans.deal==m_current.deal_ticket)related=true;if(!related&&trans.symbol==m_current.symbol&&trans.type==TRADE_TRANSACTION_DEAL_ADD)related=true;if(!related)return; if(trans.order>0)m_current.order_ticket=trans.order;if(trans.deal>0)m_current.deal_ticket=trans.deal;if(trans.position>0)m_current.position_id=trans.position;if(result.retcode>0)m_current.retcode=result.retcode; if(trans.type==TRADE_TRANSACTION_DEAL_ADD){m_current.filled_volume+=trans.volume;m_current.state=(m_current.filled_volume+1e-8>=m_current.requested_volume?AS_EXEC_FILLED:AS_EXEC_PARTIALLY_FILLED);} else if(trans.type==TRADE_TRANSACTION_POSITION)m_current.state=AS_EXEC_POSITION_ACTIVE; else if(trans.type==TRADE_TRANSACTION_ORDER_DELETE&&m_current.filled_volume<=0)m_current.state=AS_EXEC_RECONCILING; m_current.updated_at=TimeCurrent();if(m_repo!=NULL)m_repo.SaveExecution(m_current); }
   void Reconcile(){ if(!HasUnresolved())return;m_current.state=AS_EXEC_RECONCILING;bool found=false; for(int i=PositionsTotal()-1;i>=0;i--){ulong t=PositionGetTicket(i);if(t==0)continue;if(PositionGetString(POSITION_SYMBOL)==m_current.symbol&&(ulong)PositionGetInteger(POSITION_MAGIC)==AS_MAGIC){m_current.position_id=(ulong)PositionGetInteger(POSITION_IDENTIFIER);m_current.state=AS_EXEC_POSITION_ACTIVE;found=true;break;}} if(!found&&TimeCurrent()-m_current.updated_at>30){m_current.state=AS_EXEC_UNKNOWN;m_current.message="RECONCILIATION_UNRESOLVED";} m_current.updated_at=TimeCurrent();if(m_repo!=NULL)m_repo.SaveExecution(m_current); }
};
